### ISSUE TITLE
Question: Is there a way to us this without using webpack?

### ISSUE THREAD

**Issue by pineapplejoe** [ai/audio-recorder-polyfill#44]
Would like to use it but not sure how to utilize it without having to change it first. thanks.

**Comment by ai** [comment]
Our `index.js` has no webpack feature. You can put it directly to the browser and it should work.

But I do not recommend it, because avoiding a bundler could dramatically affects performance.

If you do not want to configure webpack (it is really hard and non-intuitive) I recommend to look at Parcel bundler. It is really powerful and easy to use.

**Comment by pineapplejoe** [comment]
Thanks.

Previously tried to load index.js but it spit out

index.js:276 Uncaught ReferenceError: require is not defined

which is this line

MediaRecorder.encoder = require('./wave-encoder')

thought require was brought in by webpack but I guess not? 

We looked at Webpack before and it looked like it was going to not work for us.  

Will look at parcel to see if it could work for us.

**Comment by ai** [comment]
Oh. I forgot about that `require`. In this case, there is no simple way to do it.

Use Parcel.

**Comment by pineapplejoe** [comment]
Welp - looks like there are some compat issues  with parcel and ejs (which we use).  

I guess we'll keep looking.  

thanks
